# Welcome to Jekyll!

# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Ali Goli | Assistant Professor of Marketing"
title_separator: "-"
name: &name "Ali Goli"
description: &description "Assistant Professor of Marketing at Foster School of Business, University of Washington"
url: "https://golialii.github.io"
baseurl: ""
repository: "golialii/golialii.github.io"

# Site Author
author:
  avatar: "profile.png"
  name: "Ali Goli"
  bio: "Assistant Professor of Marketing at Foster School of Business, University of Washington"
  email: "agoli@uw.edu"
  location: "Seattle, WA"
  employer: "University of Washington"
  googlescholar: "https://scholar.google.com/citations?user=XDN3XggAAAAJ&hl=en&oi=ao"
  linkedin: "ali-goli-b6981597"
  twitter: "golialii"
  github: "golialii"

# Navigation
nav:
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /files/Ali_Goli_CV.pdf

# Site Settings
teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Comments (disabled)
comments:
  provider: false

# RSS
atom_feed:
  hide: false

# Analytics (disabled)
analytics:
  provider: false

# Social
twitter:
  username: &twitter "golialii"
social:
  type: "Person"
  name: "Ali Goli"
  links:
    - "https://scholar.google.com/citations?user=XDN3XggAAAAJ&hl=en&oi=ao"
    - "https://www.linkedin.com/in/ali-goli-b6981597/"
    - "https://x.com/golialii"

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/New_York

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
