# Site Settings
locale: "en-US"
title: "Ali Goli | Assistant Professor of Marketing"
title_separator: "-"
name: "Ali Goli"
description: "Assistant Professor of Marketing at Foster School of Business, University of Washington"
url: https://goliiali.github.io
baseurl: ""
repository: "goliiali/goliiali.github.io"

# Site Author
author:
  name: "Ali Goli"
  avatar: "profile.png" # Place your profile.png in /images/
  bio: "Assistant Professor of Marketing at Foster School of Business, University of Washington"
  location: "Seattle, WA"
  employer: "University of Washington"
  googlescholar: # Add your Google Scholar profile URL
  email: "agoli@uw.edu"
  cv: "https://drive.google.com/file/d/13G5hjHf8knCMYWrJPDQMjMkQBiBLKH1T/view?usp=sharing"
  # Add your social media profiles here
