# Site Settings
locale: "en-US"
title: "Ali Goli | Assistant Professor of Marketing"
title_separator: "-"
name: "Ali Goli"
description: "Assistant Professor of Marketing at Simon Business School, University of Rochester"
url: https://goliiali.github.io
baseurl: ""
repository: "goliiali/goliiali.github.io"
github_username: "goliiali"

# Site Author
author:
  name: "Ali Goli"
  avatar: "profile.png" # Make sure to upload your profile pic to /images/ folder
  bio: "Assistant Professor of Marketing at Simon Business School, University of Rochester"
  location: "Rochester, NY"
  employer: "University of Rochester"
  googlescholar: # Add your Google Scholar URL if you have one
  email: "agoli@uw.edu"
  researchgate: # Add your ResearchGate URL if you have one
  uri: 
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: 
  google_plus:
  keybase:
  instagram:
  impactstory:
  lastfm:
  linkedin:https://www.linkedin.com/in/ali-goli-b6981597/
  orcid: 
  pinterest:
  soundcloud:
  stackoverflow: 
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:
  wikipedia:

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
      
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
